In [1]:
import numpy as np
import pandas as pd
import requests
import cfbd
from cfbd.rest import ApiException

In [2]:
dataset = pd.DataFrame()

In [3]:
# Configure API key authorization: ApiKeyAuth
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = '+eiRK37qNRqjoDcgyigTAWo4QyGrMtYR1o/hifwQmzj8hO1OwzwDdbjRnJKfSr2t'
configuration.api_key_prefix['Authorization'] = 'Bearer'

for year in range (2021, 2024):
    api_config = cfbd.ApiClient(configuration)
    for week in range (1,16):
        response = plays = cfbd.PlaysApi(api_config).get_plays(year=year, week=week, offense='Michigan')
        data = (pd.DataFrame.from_records([p.to_dict() for p in plays]))
        dataset = pd.concat([dataset, data]) 
          
      
dataset

,id,drive_id,game_id,drive_number,play_number,offense,offense_conference,offense_score,defense,home,...,yard_line,yards_to_goal,down,distance,yards_gained,scoring,play_type,play_text,ppa,wallclock
0,401282772101854401,4012827721,401282772,1,2,Michigan,Big Ten,0,Western Michigan,Michigan,...,25,75,1,10,4,False,Rush,Hassan Haskins run for 4 yds to the Mich 29,-0.114289,2021-09-04T16:04:03.000Z
1,401282772101858001,4012827721,401282772,1,3,Michigan,Big Ten,0,Western Michigan,Michigan,...,29,71,2,6,3,False,Rush,Hassan Haskins run for 3 yds to the Mich 32,-0.274866,2021-09-04T16:04:35.000Z
2,401282772101866101,4012827721,401282772,1,4,Michigan,Big Ten,0,Western Michigan,Michigan,...,32,68,3,3,11,False,Pass Reception,Cade McNamara pass complete to Erick All for 1...,2.001593,2021-09-04T16:05:24.000Z
3,401282772101868901,4012827721,401282772,1,5,Michigan,Big Ten,0,Western Michigan,Michigan,...,43,57,1,10,2,False,Rush,Hassan Haskins run for 2 yds to the Mich 45,-0.686193,2021-09-04T16:05:50.000Z
4,401282772101875401,4012827721,401282772,1,6,Michigan,Big Ten,0,Western Michigan,Michigan,...,45,55,2,8,10,False,Pass Reception,Cade McNamara pass complete to Cornelius Johns...,1.674996,2021-09-04T16:06:32.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,401539480104966102,40153948026,401539480,26,1,Michigan,Big Ten,26,Iowa,Iowa,...,65,65,4,1,0,False,Kickoff,Tommy Doman kickoff for 65 yds for a touchback,NaN,2023-12-03T04:25:30.000Z
85,401539480104987801,40153948027,401539480,27,1,Michigan,Big Ten,26,Iowa,Iowa,...,39,39,1,10,4,False,Rush,Alex Orji run for 4 yds to the IOWA 35,-0.085210,2023-12-03T04:34:04.000Z
86,401539480104995401,40153948027,401539480,27,2,Michigan,Big Ten,26,Iowa,Iowa,...,35,35,2,6,-1,False,Rush,TEAM run for a loss of 1 yard to the IOWA 36,-1.077809,2023-12-03T04:34:52.000Z
87,401539480104997901,40153948027,401539480,27,3,Michigan,Big Ten,26,Iowa,Iowa,...,36,36,3,7,-2,False,Rush,TEAM run for a loss of 2 yards to the IOWA 38,-1.460774,2023-12-03T03:51:07.000Z
88,401539480104997902,40153948027,401539480,27,4,Michigan,Big Ten,26,Iowa,Iowa,...,36,36,0,7,0,False,End of Game,End of 4th Quarter,NaN,2023-12-03T04:35:34.000Z

In [4]:
#choose data for predicting the plays. Not all data we have is going to be relevant 
data = dataset[['home', 'away', 'offense_score', 'defense_score', 'period', 'clock', 'yards_to_goal', 'down', 'distance', 'play_type']]

data

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush
1,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 19}",71,2,6,Rush
2,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 38}",68,3,3,Pass Reception
3,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 10}",57,1,10,Rush
4,Michigan,Western Michigan,0,0,1,"{'minutes': 12, 'seconds': 45}",55,2,8,Pass Reception
...,...,...,...,...,...,...,...,...,...,...
84,Iowa,Michigan,26,0,4,"{'minutes': 3, 'seconds': 38}",65,4,1,Kickoff
85,Iowa,Michigan,26,0,4,"{'minutes': 1, 'seconds': 21}",39,1,10,Rush
86,Iowa,Michigan,26,0,4,"{'seconds': 45, 'minutes': 0}",35,2,6,Rush
87,Iowa,Michigan,26,0,4,"{'seconds': 20, 'minutes': 0}",36,3,7,Rush
88,Iowa,Michigan,26,0,4,"{'minutes': 0, 'seconds': 0}",36,0,7,End of Game

In [5]:
#create column with 1 (true) and 0 (false) to see when Michihgan (team predicting for) is home or not
data['is_home'] = np.where(data['home'] == 'Michigan', 1, 0)

data.head(1)

/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/2226967805.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['is_home'] = np.where(data['home'] == 'Michigan', 1, 0)

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type,is_home
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush,1

In [6]:
pd.DataFrame(data['clock'].tolist())

      minutes  seconds
0          14       55
1          14       19
2          13       38
3          13       10
4          12       45
...       ...      ...
3443        3       38
3444        1       21
3445        0       45
3446        0       20
3447        0        0

[3448 rows x 2 columns]

In [7]:
#split clock into minutes and seconds
data[['minutes','seconds']] = pd.DataFrame(data['clock'].tolist())

data

/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/3523477563.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['minutes','seconds']] = pd.DataFrame(data['clock'].tolist())
/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/3523477563.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['minutes','seconds']] = pd.DataFrame(data['clock'].tolist())

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type,is_home,minutes,seconds
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush,1,14,55
1,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 19}",71,2,6,Rush,1,14,19
2,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 38}",68,3,3,Pass Reception,1,13,38
3,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 10}",57,1,10,Rush,1,13,10
4,Michigan,Western Michigan,0,0,1,"{'minutes': 12, 'seconds': 45}",55,2,8,Pass Reception,1,12,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Iowa,Michigan,26,0,4,"{'minutes': 3, 'seconds': 38}",65,4,1,Kickoff,0,10,49
85,Iowa,Michigan,26,0,4,"{'minutes': 1, 'seconds': 21}",39,1,10,Rush,0,10,42
86,Iowa,Michigan,26,0,4,"{'seconds': 45, 'minutes': 0}",35,2,6,Rush,0,8,35
87,Iowa,Michigan,26,0,4,"{'seconds': 20, 'minutes': 0}",36,3,7,Rush,0,8,16
88,Iowa,Michigan,26,0,4,"{'minutes': 0, 'seconds': 0}",36,0,7,End of Game,0,8,9

In [8]:
#get total seconds remaining now
data['seconds_remaining'] = ((data['minutes'] * 60) + data['seconds'])

data

/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/1494250617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['seconds_remaining'] = ((data['minutes'] * 60) + data['seconds'])

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type,is_home,minutes,seconds,seconds_remaining
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush,1,14,55,895
1,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 19}",71,2,6,Rush,1,14,19,859
2,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 38}",68,3,3,Pass Reception,1,13,38,818
3,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 10}",57,1,10,Rush,1,13,10,790
4,Michigan,Western Michigan,0,0,1,"{'minutes': 12, 'seconds': 45}",55,2,8,Pass Reception,1,12,45,765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Iowa,Michigan,26,0,4,"{'minutes': 3, 'seconds': 38}",65,4,1,Kickoff,0,10,49,649
85,Iowa,Michigan,26,0,4,"{'minutes': 1, 'seconds': 21}",39,1,10,Rush,0,10,42,642
86,Iowa,Michigan,26,0,4,"{'seconds': 45, 'minutes': 0}",35,2,6,Rush,0,8,35,515
87,Iowa,Michigan,26,0,4,"{'seconds': 20, 'minutes': 0}",36,3,7,Rush,0,8,16,496
88,Iowa,Michigan,26,0,4,"{'minutes': 0, 'seconds': 0}",36,0,7,End of Game,0,8,9,489

In [9]:
data['play_type'].unique()

array(['Rush', 'Pass Reception', 'Passing Touchdown', 'Penalty',
       'Field Goal Good', 'Kickoff', 'Pass Incompletion', 'Punt',
       'Rushing Touchdown', 'Timeout', 'Fumble Recovery (Own)',
       'End of Game', 'End Period', 'Field Goal Missed', 'End of Half',
       'Pass Interception Return', 'Sack', 'Fumble Recovery (Opponent)',
       'Kickoff Return (Offense)', 'Blocked Field Goal',
       'Interception Return Touchdown', 'Blocked Punt Touchdown',
       'Interception'], dtype=object)

In [10]:
#define each plays type
pass_types = ['Pass Reception', 'Pass Interception Return', 'Pass Incompletion', 'Sack', 'Passing Touchdown', 'Interception Return Touchdown']
rush_types = ['Rush', 'Rushing Touchdown']
punt_types = ['Punt', 'Punt Return Touchdown', 'Blocked Punt', 'Blocked Punt Touchdown']
fg_types = ['Field Goal Good', 'Field Goal Missed', 'Blocked Field Goal']

#write function to get the play type into the dataframe
def getPlayCall(x):
    if x in pass_types:
            return 'pass'
    elif x in rush_types:
        return 'rush'
    elif x in punt_types:
        return 'punt'
    elif x in fg_types:
        return 'fg'
    else:
        return None

#get the play type into the dataframe
data['play_call'] = data['play_type'].apply(getPlayCall)


data.head()

/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/1887591825.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['play_call'] = data['play_type'].apply(getPlayCall)

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type,is_home,minutes,seconds,seconds_remaining,play_call
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush,1,14,55,895,rush
1,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 19}",71,2,6,Rush,1,14,19,859,rush
2,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 38}",68,3,3,Pass Reception,1,13,38,818,pass
3,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 10}",57,1,10,Rush,1,13,10,790,rush
4,Michigan,Western Michigan,0,0,1,"{'minutes': 12, 'seconds': 45}",55,2,8,Pass Reception,1,12,45,765,pass

In [11]:
#drop the rows with 'none' as play type

data.dropna(subset=['play_call'], inplace = True)

data.head()

/var/folders/gc/l9nrmd0j3fxcb8_827d4qyk40000gn/T/ipykernel_20203/3495043873.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(subset=['play_call'], inplace = True)

,home,away,offense_score,defense_score,period,clock,yards_to_goal,down,distance,play_type,is_home,minutes,seconds,seconds_remaining,play_call
0,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 55}",75,1,10,Rush,1,14,55,895,rush
1,Michigan,Western Michigan,0,0,1,"{'minutes': 14, 'seconds': 19}",71,2,6,Rush,1,14,19,859,rush
2,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 38}",68,3,3,Pass Reception,1,13,38,818,pass
3,Michigan,Western Michigan,0,0,1,"{'minutes': 13, 'seconds': 10}",57,1,10,Rush,1,13,10,790,rush
4,Michigan,Western Michigan,0,0,1,"{'minutes': 12, 'seconds': 45}",55,2,8,Pass Reception,1,12,45,765,pass

In [12]:
plays = data[['offense_score', 'defense_score', 'period', 'yards_to_goal', 'down', 'distance', 'is_home', 'seconds_remaining', 'play_call']]

plays.head()

,offense_score,defense_score,period,yards_to_goal,down,distance,is_home,seconds_remaining,play_call
0,0,0,1,75,1,10,1,895,rush
1,0,0,1,71,2,6,1,859,rush
2,0,0,1,68,3,3,1,818,pass
3,0,0,1,57,1,10,1,790,rush
4,0,0,1,55,2,8,1,765,pass

In [13]:
#import training and test split and randm forest clssifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [14]:
#split the data between out independent variables (the stuff used to predict) and the dependent variable (the thing we are trying to predict (the play call))
play_calls = plays['play_call']
plays = plays.drop(['play_call'], axis = 1)

In [15]:
#split the data into training and test sets
plays_train, plays_validation, calls_train, calls_validation = train_test_split(plays, play_calls, train_size=0.8, test_size=0.2, random_state=0)
plays_train.head()

,offense_score,defense_score,period,yards_to_goal,down,distance,is_home,seconds_remaining
18,7,7,1,26,3,8,0,832
4,0,0,1,51,1,10,0,765
79,23,10,4,35,1,10,0,806
80,24,10,4,9,2,5,0,800
62,28,0,2,10,1,10,0,569

In [16]:
#convert our play calls (pass, rush, punt, fg) to numeric for predicting
y, y_keys = pd.factorize(calls_train)

In [17]:
#build the classifier
classifier = RandomForestClassifier(random_state=0, n_estimators=100)

# train the classifier with our test set
classifier.fit(plays_train, y)

RandomForestClassifier(random_state=0)

In [18]:
classifier.predict(plays_validation)

array([0, 1, 0, 3, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 3, 3, 1, 1, 3, 0, 1, 0, 2, 1, 3, 0, 1, 0, 0, 0, 2, 0,
       0, 3, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 3, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 3, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 3, 1, 3, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 3, 0, 0, 1, 0, 1, 3,
       1, 0, 1, 3, 0, 1, 1, 0, 1, 3, 0, 0, 1, 1, 1, 0, 1, 1, 0, 3, 1, 3,
       1, 0, 1, 1, 1, 3, 1, 1, 1, 3, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 3, 1, 0, 1, 0, 1, 1, 0, 1, 2, 3, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 3, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 3, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 3, 3, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 3, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 3, 1, 1, 2, 1, 1, 1, 3, 0,
       1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 0, 3, 0, 3, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 3, 1, 1, 0, 3, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 3, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1])

In [19]:
(classifier.predict_proba(plays_validation)[0:10]).tolist()

[[0.73, 0.26, 0.0, 0.01],
 [0.18, 0.8, 0.0, 0.02],
 [0.56, 0.44, 0.0, 0.0],
 [0.05, 0.1, 0.1, 0.75],
 [0.054000000000000006, 0.946, 0.0, 0.0],
 [0.53, 0.46, 0.0, 0.01],
 [0.24, 0.76, 0.0, 0.0],
 [0.45, 0.55, 0.0, 0.0],
 [0.26, 0.74, 0.0, 0.0],
 [0.17, 0.83, 0.0, 0.0]]

In [20]:
#map labels back to preidctions
predicted_calls = y_keys[classifier.predict(plays_validation)]

predicted_calls

Index(['pass', 'rush', 'pass', 'punt', 'rush', 'pass', 'rush', 'rush', 'rush',
       'rush',
       ...
       'pass', 'rush', 'rush', 'rush', 'pass', 'rush', 'rush', 'rush', 'rush',
       'rush'],
      dtype='object', length=556)

In [21]:
#compare predicted to actual output
pd.crosstab(calls_validation, predicted_calls, rownames=['Actual Calls'], colnames=['Predicted Calls'])

Predicted Calls  fg  pass  punt  rush
Actual Calls
fg                9     0     0     0
pass              0   106     3   113
punt              0     0    28     0
rush              1    74     2   220

In [22]:
#see where most of the 'weight' of our predictions is at
list(zip(plays_train, classifier.feature_importances_))

[('offense_score', 0.1239172911215789),
 ('defense_score', 0.08250913656201841),
 ('period', 0.04419239699535806),
 ('yards_to_goal', 0.246571055205977),
 ('down', 0.1613302321520657),
 ('distance', 0.1286043625205124),
 ('is_home', 0.027157162933301),
 ('seconds_remaining', 0.18571836250918858)]

In [23]:
# incorporate period into seconds_remaining
plays['seconds_remaining'] = ((4 - plays['period']) * 15 * 60 ) + plays['seconds_remaining']

# drop is_home and period columns
plays = plays.drop(columns=['is_home', 'period'])

In [24]:
plays

,offense_score,defense_score,yards_to_goal,down,distance,seconds_remaining
0,0,0,75,1,10,3595
1,0,0,71,2,6,3559
2,0,0,68,3,3,3518
3,0,0,57,1,10,3490
4,0,0,55,2,8,3465
...,...,...,...,...,...,...
81,23,0,36,3,5,765
83,26,0,32,4,1,705
85,26,0,39,1,10,642
86,26,0,35,2,6,515
87,26,0,36,3,7,496

In [25]:
plays_train, plays_validation, calls_train, calls_validation = train_test_split(plays, play_calls, train_size=0.8, test_size=0.2, random_state=0)
y, y_keys = pd.factorize(calls_train)

classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(plays_train, y)

predicted_calls = y_keys[classifier.predict(plays_validation)]

pd.crosstab(calls_validation, predicted_calls, rownames=['Actual Calls'], colnames=['Predicted Calls'])

Predicted Calls  fg  pass  punt  rush
Actual Calls
fg                9     0     0     0
pass              1   106     2   113
punt              0     0    26     2
rush              0    69     0   228

In [26]:
#see where most of the 'weight' of our predictions is at
list(zip(plays_train, classifier.feature_importances_))

[('offense_score', 0.13094771860568746),
 ('defense_score', 0.08758551473624937),
 ('yards_to_goal', 0.2724938016080439),
 ('down', 0.1568834681662927),
 ('distance', 0.12571570907181306),
 ('seconds_remaining', 0.22637378781191353)]

In [27]:
# calculate new scoring margin field and drop the individual score columns. Find out how much who we are prediciting for is down or up
plays['margin'] = plays['offense_score'] - plays['defense_score']
plays = plays.drop(columns=['offense_score', 'defense_score'])
plays

    yards_to_goal  down  distance  seconds_remaining  margin
0              75     1        10               3595       0
1              71     2         6               3559       0
2              68     3         3               3518       0
3              57     1        10               3490       0
4              55     2         8               3465       0
..            ...   ...       ...                ...     ...
81             36     3         5                765      23
83             32     4         1                705      26
85             39     1        10                642      26
86             35     2         6                515      26
87             36     3         7                496      26

[2777 rows x 5 columns]

In [28]:
plays_train, plays_validation, calls_train, calls_validation = train_test_split(plays, play_calls, train_size=0.8, test_size=0.2, random_state=0)
y, y_keys = pd.factorize(calls_train)

classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(plays_train, y)

predicted_calls = y_keys[classifier.predict(plays_validation)]

pd.crosstab(calls_validation, predicted_calls, rownames=['Actual Calls'], colnames=['Predicted Calls'])

Predicted Calls  fg  pass  punt  rush
Actual Calls
fg                9     0     0     0
pass              1   112     2   107
punt              0     0    26     2
rush              0    63     0   234

In [29]:
list(zip(plays_train, classifier.feature_importances_))

[('yards_to_goal', 0.29609474225599336),
 ('down', 0.15554404442606776),
 ('distance', 0.1287466386539196),
 ('seconds_remaining', 0.252087607935222),
 ('margin', 0.16752696672879736)]

In [30]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(calls_validation, predicted_calls)
accuracy

0.685251798561151

In [31]:
classifier.predict_proba(plays_validation)[0:10]

array([[0.62      , 0.37      , 0.01      , 0.        ],
       [0.29      , 0.71      , 0.        , 0.        ],
       [0.49      , 0.51      , 0.        , 0.        ],
       [0.01      , 0.03      , 0.13      , 0.83      ],
       [0.21      , 0.79      , 0.        , 0.        ],
       [0.4       , 0.6       , 0.        , 0.        ],
       [0.03      , 0.97      , 0.        , 0.        ],
       [0.40066667, 0.59933333, 0.        , 0.        ],
       [0.14      , 0.86      , 0.        , 0.        ],
       [0.15      , 0.85      , 0.        , 0.        ]])

In [32]:
#create function used to predict plays
def predict_call(yards, down, distance, seconds, margin):
    test_plays = pd.DataFrame({'yards_to_goal': [yards], 'down': [down], 'distance': [distance], 'seconds_remaining': [seconds], 'margin': [margin]})
    call = (classifier.predict_proba(test_plays)[0]).tolist()
    columns = ['PROBA']
    columnsx=y_keys[classifier.classes_].to_list()
    columnsx
    rows = columnsx
    data = call
    df = pd.DataFrame(data=data, index=rows, columns=columns)
    df['PROBA']=df['PROBA']*100
    df = df.transpose()
    return df
    # return y_keys[classifier.predict(test_plays)][0]

In [33]:
call = predict_call(20,4,15,10,-4)
call

       pass  rush    fg  punt
PROBA  19.0   9.0  66.0   6.0