In [3]:
import numpy as np
import pandas as pd

In [4]:
train_data = pd.read_csv("./input/train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
test_data = pd.read_csv("./input//test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
#add column senior citizen to data

train_data.loc[train_data['Age'] < 65, 'SeniorCit'] = 0
train_data.loc[train_data['Age'] >= 65, 'SeniorCit'] = 1


test_data.loc[test_data['Age'] < 65, 'SeniorCit'] = 0
test_data.loc[test_data['Age'] >= 65, 'SeniorCit'] = 1

In [7]:
train_data.head()
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SeniorCit
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0.0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0.0
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0.0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0.0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0.0

In [8]:
#drop columns
train_data.drop(['Name', 'Ticket'], axis=1, inplace=True)

In [9]:
train_data['FOB'] = (train_data['SibSp'] + train_data['Parch'])
test_data['FOB'] = (test_data['SibSp'] + test_data['Parch'])

train_data.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,SeniorCit,FOB
0,1,0,3,male,22.0,1,0,7.2500,NaN,S,0.0,1
1,2,1,1,female,38.0,1,0,71.2833,C85,C,0.0,1
2,3,1,3,female,26.0,0,0,7.9250,NaN,S,0.0,0
3,4,1,1,female,35.0,1,0,53.1000,C123,S,0.0,1
4,5,0,3,male,35.0,0,0,8.0500,NaN,S,0.0,0

In [10]:
#drop columns
train_data.drop(['SibSp', 'Parch'], axis=1, inplace=True)

In [11]:
train_data.head()

,PassengerId,Survived,Pclass,Sex,Age,Fare,Cabin,Embarked,SeniorCit,FOB
0,1,0,3,male,22.0,7.2500,NaN,S,0.0,1
1,2,1,1,female,38.0,71.2833,C85,C,0.0,1
2,3,1,3,female,26.0,7.9250,NaN,S,0.0,0
3,4,1,1,female,35.0,53.1000,C123,S,0.0,1
4,5,0,3,male,35.0,8.0500,NaN,S,0.0,0

In [12]:
# Extract feature and target arrays
X, y = train_data.drop('Survived', axis=1), train_data[['Survived']]

In [13]:
features = ["Pclass", "Sex", "Age", "FOB", "Fare", "SeniorCit"]

X = pd.get_dummies(X[features])
X_test = pd.get_dummies(test_data[features])

In [14]:
X_test

     Pclass   Age  FOB      Fare  SeniorCit  Sex_female  Sex_male
0         3  34.5    0    7.8292        0.0       False      True
1         3  47.0    1    7.0000        0.0        True     False
2         2  62.0    0    9.6875        0.0       False      True
3         3  27.0    0    8.6625        0.0       False      True
4         3  22.0    2   12.2875        0.0        True     False
..      ...   ...  ...       ...        ...         ...       ...
413       3   NaN    0    8.0500        NaN       False      True
414       1  39.0    0  108.9000        0.0        True     False
415       3  38.5    0    7.2500        0.0       False      True
416       3   NaN    0    8.0500        NaN       False      True
417       3   NaN    2   22.3583        NaN       False      True

[418 rows x 7 columns]

In [15]:
import xgboost as xgb

model = xgb.XGBClassifier(n_estimators=200, objective='binary:logistic', tree_method='hist', eta=0.1, max_depth=3, enable_categorical=True)

In [16]:
model.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eta=0.1, eval_metric=None,
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None, ...)

In [17]:
preds = model.predict(X_test)

In [18]:
preds

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])